### ISSUE TITLE
Verizon validation error

### ISSUE THREAD

**Issue by pke11y** [networktocode/circuit-maintenance-parser#136]
### Environment

- Python version:  3.8.7
- circuit_maintenance_parser version: 2.0.7

### Expected Behavior

Notification parsed successfully

### Observed Behavior

Notification parsing fails. No `maintenance_id`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nautobot_circuit_maintenance/handle_notifications/handler.py", line 234, in get_maintenances_from_notification
    result = parser_provider.get_maintenances(data_to_process)
  File "/usr/local/lib/python3.8/site-packages/circuit_maintenance_parser/provider.py", line 136, in get_maintenances
    raise ProviderError(
circuit_maintenance_parser.errors.ProviderError: Failed creating Maintenance notification for Verizon.
Details:
- Processor CombinedProcessor from Verizon failed due to: 1 validation error for Maintenance
maintenance_id
  field required (type=value_error.missing)
```

**Comment by chadell** [comment]
@pke11y could you provide more info? input data? I don't see the tests failing
