### ISSUE TITLE
Zayo email fails parser on email signature

### ISSUE THREAD

**Issue by jmaslak** [networktocode/circuit-maintenance-parser#175]
### Environment

- Python version: 3.9.6
- circuit_maintenance_parser version: 2.1.0

### Expected Behavior

Properly parse the email attached.

### Observed Behavior

```
$ circuit-maintenance-parser --data-file a.eml --data-type email --provider-type zayo
Traceback (most recent call last):
  File "/home/jmaslak/.pyenv/versions/3.9.6/bin/circuit-maintenance-parser", line 8, in <module>
    sys.exit(main())
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/circuit_maintenance_parser/cli.py", line 47, in main
    parsed_notifications = provider.get_maintenances(data)
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/circuit_maintenance_parser/provider.py", line 118, in get_maintenances
    if self.exclude_filter_check(data) or not self.include_filter_check(data):
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/circuit_maintenance_parser/provider.py", line 79, in include_filter_check
    return self.filter_check(self._include_filter, data, "include")
  File "/home/jmaslak/.pyenv/versions/3.9.6/lib/python3.9/site-packages/circuit_maintenance_parser/provider.py", line 97, in filter_check
    data_part_content = data_part.content.decode().replace("\r", "").replace("\n", "")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 2254: invalid continuation byte
```

### Steps to Reproduce

See above.  The problem in the email appears to be the =C9's in the raw .EML file, that is part of the email signature.  Note I annonymized key aspects of the EML file but that does not restrict reproduction of the bug.  I have gzipped and attached the email file (since Github doesn't allow an EML that isn't zipped).

[a.eml.gz](https://github.com/networktocode/circuit-maintenance-parser/files/9833392/a.eml.gz)

**Comment by jarriagad** [comment]
Hello,

I'm currently running into this issue as well.

My current workaround is to remove the invalid chars from the original text by first ascii decoding the email raw bytes and passing that string to the function below:

```
def _ascii_normalize(text: str) -> str:
   return "".join(char for char in text if ord(char) < 128)
```
This can then be utf-8 encoded and passed to the parser.


I think an upstream solution would be to add encoding detection before the data_part is decoded in the `filter_check` function
I have tested this solution locally and have not seen any problems:

in file `circuit_maintenance_parser/provider.py`

```
import chardet

@staticmethod
    def filter_check(filter_dict: Dict, data: NotificationData, filter_type: str) -> bool:
        """Generic filter check."""
        data_part_content = None
        for data_part in data.data_parts:
            filter_data_type = data_part.type
            if filter_data_type not in filter_dict:
                continue
            data_part_content_encoding = chardet.detect(data_part.content).get('encoding', 'utf-8')
            data_part_content = data_part.content.decode(data_part_content_encoding).replace("\r", "").replace("\n", "")
            if any(re.search(filter_re, data_part_content) for filter_re in filter_dict[filter_data_type]):
                logger.debug("Matching %s filter expression for %s.", filter_type, data_part_content)
                return True```


Thank you

**Comment by jasonyates** [comment]
This fix works for me with Zayo's latest maintenance notifications. Are there plans to build a new release any time soon so I don't have to install from git?

**Comment by chadell** [comment]
@jasonyates It was released yesterday: https://github.com/networktocode/circuit-maintenance-parser/releases/tag/v2.2.1

Unfortunately, we have to fix the publish to github, but, the pypi one is already available
