### ISSUE TITLE
Version 1.2.0 is not backwards-compatible with version 1.1.0 or nautobot-circuit-maintenance 0.1.3

### ISSUE THREAD

**Issue by glennmatthews** [networktocode/circuit-maintenance-parser#30]
### Environment

- Python version: 
- circuit_maintenance_parser version: 1.2.0

### Expected Behavior

Backwards compatibility in minor-version-incrementing releases.

### Observed Behavior

The `MaintenanceNotification` model was renamed to `Parser` by #26, meaning that any code (such as version 0.1.3 of https://github.com/nautobot/nautobot-plugin-circuit-maintenance) that makes use of this model will fail when attempting to import it:

```
 Traceback (most recent call last):
   File "/usr/local/bin/nautobot-server", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.7/site-packages/nautobot/core/cli.py", line 62, in main
     initializer=_configure_settings,  # Called after defaults
   File "/usr/local/lib/python3.7/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
     management.execute_from_command_line([runner_name, command] + command_args)
   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
     utility.execute()
   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
     django.setup()
   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
     app_config.ready()
   File "/usr/local/lib/python3.7/site-packages/nautobot_circuit_maintenance/__init__.py", line 68, in ready
     super().ready()
   File "/usr/local/lib/python3.7/site-packages/nautobot/extras/plugins/__init__.py", line 92, in ready
     jobs = import_object(f"{self.__module__}.{self.jobs}")
   File "/usr/local/lib/python3.7/site-packages/nautobot/extras/plugins/utils.py", line 44, in import_object
     spec.loader.exec_module(module)
   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/usr/local/lib/python3.7/site-packages/nautobot_circuit_maintenance/jobs.py", line 2, in <module>
     from .handle_notifications.handler import HandleCircuitMaintenanceNotifications
   File "/usr/local/lib/python3.7/site-packages/nautobot_circuit_maintenance/handle_notifications/handler.py", line 6, in <module>
     from circuit_maintenance_parser import ParsingError, init_parser, MaintenanceNotification
 ImportError: cannot import name 'MaintenanceNotification' from 'circuit_maintenance_parser' (/usr/local/lib/python3.7/site-packages/circuit_maintenance_parser/__init__.py)
```

### Steps to Reproduce

1.
2.
3.

**Comment by chadell** [comment]
fixed in #32
